# Dev-only configuration. Anonymous access is enabled for local development.
# DO NOT use this configuration in production.
persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type all

listener 1883 0.0.0.0
allow_anonymous true
